services:
  # LocalStack for AWS Services emulation
  localstack:
    container_name: book-mgmt-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"      # LocalStack edge endpoint
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-docker}
      - LAMBDA_REMOTE_DOCKER=false
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=lambda,apigateway,dynamodb,s3,cloudfront,iam,logs
      - PERSISTENCE=1
      - DATA_DIR=/opt/localstack/data
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - LS_LOG=${LS_LOG:-warn}
      - ENFORCE_IAM=0  # Disable IAM for development
      - TMPDIR=/opt/localstack/tmp
    volumes:
      - "./localstack-data:/opt/localstack/data"
      - "./localstack-tmp:/opt/localstack/tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./backend:/opt/code/backend"  # Mount backend code
      - "./logs/localstack:/var/log/localstack"  # Mount logs directory
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # [Rest of the services remain the same...]